export const BACKEND_URL = 'https://gossips.crishav01.workers.dev/api/v1'
export const SIGNUP = '/user/signup'
export const SIGNIN = '/user/signin'
export const GET_ALL_BLOGS = '/blog/bulk'
export const GET_BLOG_BY_ID = '/blog/'
export const UPDATE_BLOG = '/blog'
export const CREATE_BLOG = '/blog'